### ISSUE TITLE
Избавиться от define в файлах (h, cpp)

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#16]
Заменить define определения литералов на константы
Макро-функции заменить на функции
Для общих констант определить общий заголовочный файл

**Comment by dmpas** [comment]
с MAX и MIN бывают косяки, когда аргументы разного типа. В случае с макросом получается просто предупреждение (если знаковость разная), а в случае с std::min и std::max получается настоящая ошибка, что функция для таких типов не определена.

**Comment by andreevlex** [comment]
Это тогда получается неявное приведение типов... Надо где возможно явно объяснить компилятору, что мы от него хотим.

**Comment by dmpas** [comment]
Надо быть готовым к тому, что таких мест будет много.

**Comment by andreevlex** [comment]
> Надо быть готовым к тому, что таких мест будет много.

Для MIN, MAX можно шаблон замутить со специализацией. 
Проверка типов будет при компиляции

**Comment by andreevlex** [comment]
`#define CHUNK 65536` есть, а ни где в APIcfBase.cpp и Class_1CD.cpp, ConfigStorage.cpp не используется. Удалю?

**Comment by dmpas** [comment]
Удаляй.

**Comment by andreevlex** [comment]
Нам это надо? CRC32 в проекте нет.
```c++
#ifndef getcfname
#include "CRC32.h"
#endif
```

**Comment by dmpas** [comment]
> Нам это надо? CRC32 в проекте нет.

поглядывай время от времени в ветку master - там почти нетронутые исходники, там можно увидеть, использовался ли вообще CRC32. Скорее всего при вычленении консольной части оно стало не нужно, но с перспективой на то, что когда-нибудь мы снова будем прикручивать гуй, придётся обратно вкручивать и подобные куски. Так что глянь мастер, посмотри, как там оно использовалось, и реши - выпилить нафиг или оставить на будущее с пометкой.

**Comment by andreevlex** [comment]
в master вызов _crc32 находится в закомментированном коде.
Удалю закомментированный код(прогладел) и этот #ifndef с файлами CRC32.*

**Comment by andreevlex** [comment]
вот этого define реально очень много.
```c++
#define error if(msreg) msreg->AddError
```
Надо подумать как заменить глобальный error
1. Глобальная функция с параметром `String& message`
2. Хранить ссылку на MessageRegistrator в каждом классе
3. Создать абстрактный класс, который содержит MessageRegistrator и сделать метод error

**Comment by andreevlex** [comment]
По идее регистратор сообщений должен быть один на всю программу.
> исключаем возможность msreg быть nullptr

согласен

> создаём класс-наследник от мессенджера, в котором AddError ничего не делает, и в случаях, когда msreg не задаётся явно, брать экземпляр нового класса.

Мысль не уловил.

**Comment by dmpas** [comment]
> один на всю программу

Одиночка - опасный шаблон.

> Мысль не уловил.

Передавать не нуллптр, а экземпляр класса, который ничего не делает (тот же MessageRegistration)

**Comment by andreevlex** [comment]
А почему ничего не делает? мы не хотим регистрировать данные ошибки?

**Comment by dmpas** [comment]
само по себе условие 
```c++
if (msreg) ...
```

предполагает, что мы ничего не делаем, если там `nullptr`. Соответственно, если вызывающий код передаёт `nullptr`, он хочет, чтобы ошибки не регистрировались - это поведение мы и хотим сохранить.

**Comment by andreevlex** [comment]
ааа понял.
