### ISSUE TITLE
Исправить предупреждения при сборке x64-Linux

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#18]
SystemClasses/TMemoryStream.cpp|32|предупреждение: сравнение знакового и беззнакового целых выражений [-Wsign-compare]|
SystemClasses/TStream.cpp|83|предупреждение: сравнение знакового и беззнакового целых выражений [-Wsign-compare]|

**Comment by andreevlex** [comment]
Тут  SystemClasses/TMemoryStream.cpp|32| 
m_position `int64_t`, а _data.size() `size_t`
```c++
if (_data.size() <= m_position + toRead) {
```

**Comment by dmpas** [comment]
Напомню на всякий случай, что от систем.классес по возможности надо отказываться, и фиксить только при необходимости.

**Comment by andreevlex** [comment]
хорошо, максимально игнорим system.clases

**Comment by andreevlex** [comment]
@dmpas на что будем менять TStream и ему подобные. В буст есть чего?

**Comment by dmpas** [comment]
iostream, fstream. по обстоятельствам.
