### ISSUE TITLE
Перенос функционала

### ISSUE THREAD

**Issue by dmpas** [dmpas/tool1cd#2]
* [x] ExportAllToXML

* [x] ExportToXML

* [x] BlobToFile

* [x] ParseBlob

* [x] DumpConfig

* [x] DumpDBConfig

* [x] DumpVendorsConfigs

* [x] DumpAllConfigs

* [x] DumpDepotConfig

* [x] DumpPartDepotConfig

**Comment by andreevlex** [comment]
Помощь нужна?

**Comment by dmpas** [comment]
@andreevlex  да я б не отказался :) 
тут у нас гиттер для общения: https://gitter.im/Tool_1CD/Tool_1CD

**Comment by ava57r** [comment]
Может обновим статусы переноса функционала, что у нас точно работает из перечисленного?

**Comment by dmpas** [comment]
Вот только утром про это думал. Надо обновить, конечно же.

**Comment by ava57r** [comment]
DumpDepotConfig - проверено на версиях 5, 6, 7 со снапшотами и без
Выгруженные конфигурации успешно загрузились в 1с-ку

**Comment by dmpas** [comment]
Отметил `DumpConfig` и `DumpDBConfig`. Вендорс чего-то у меня не сработал.

**Comment by ava57r** [comment]
Поставил
- DumpVendorsConfigs
- DumpAllConfigs

**Comment by dmpas** [comment]
Юхууу! функционал переколбашен! Остальные косяки - отдельными задачками.
