### ISSUE TITLE
Определить общий тип хранения строки и строковых литералов

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#23]
Какие строки будем использовать?
1. Широкие L""
2. UTF-8

**Comment by fishca** [comment]
1C использует UTF-8 думаю есть смысл их и использовать

**Comment by andreevlex** [comment]
насколько я осведомлен внутри себя использует UTF-16.

**Comment by andreevlex** [comment]
парсить, то сами файлы 1с-ки мы будем как здесь задано текущим кодом. 
Я предлагаю для:
 - сообщений пользователям
 - записи в логи и т.д.

Проект под винду собирается с настройками "многобайтовая unicode"

**Comment by dmpas** [comment]
Нафиг-нафиг многобайтовый уникод. В си++ всё же принят обычный string. Винда-невинда - огребём на двоякости кода.
