### ISSUE TITLE
Неявное приведение типов размера данных при распаковке

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#28]
Как-то все это выглядет не правильно
srcSize - типа uintmax_t 
src->GetSize() возвращает тип int64_t
src->Read(srcBuf, srcSize) принимает 2-м параметром тип int64_t

ctool1cd/UZLib.cpp
```c++
void ZInflateStream(TStream* src, TStream* dst)
{
	...
	uintmax_t srcSize;
...
		srcSize = src->GetSize();         // определяем размер данных
		src->Read(srcBuf, srcSize);  // читаем из потока в буфер данные
strm.avail_in = srcSize;
```

**Comment by andreevlex** [comment]
Для для задания размерной величины предлагаю тип size_t, его используют стандартные контейнеры,да и вообще рекомендуют для этих целей.

**Comment by dmpas** [comment]
`int64_t` был введён в SystemClasses только согласно документации от Embarcadero. От SystemClasses мы откажемся, потому сейчас это не принципиально. В остальных местах нужно попутно приводить к `size_t`.

**Comment by andreevlex** [comment]
Кто же у них пишет документацию? Рекомендуют тип со знаком для указания размера списка...
Надо планировать замену dynamic array.

**Comment by dmpas** [comment]
Наследие паскаля - там не особо-то принято пользоваться беззнаковыми типами.

**Comment by ava57r** [comment]
Разрабы C++ Builder нормальные парни 
https://www.viva64.com/ru/t/0072/ - Бесконечный цикл
В Qt тоже используют знаковые типы.

**Comment by ava57r** [comment]
кода обозначенного в задаче уже нет в UZip.cpp
