### ISSUE TITLE
Не производится выгрузка данных blob (HISTORY, EXTERNALS ...) при использовании ключа -eax

### ISSUE THREAD

**Issue by fishca** [dmpas/tool1cd#32]
Создаются пустые файлы данных при выгрузке с ключем "-eax" в каталог blob размером в 16 байт.
![06_06_1](https://cloud.githubusercontent.com/assets/1484649/26825205/cd41be74-4abc-11e7-9f1f-b6fa6b5bd84e.png)

[1cv8ddb.zip](https://github.com/dmpas/tool1cd/files/1054653/1cv8ddb.zip) - файл хранилища 1С

**Comment by fishca** [comment]
![06_06_1](https://cloud.githubusercontent.com/assets/1484649/26825645/86f08d2c-4abe-11e7-9935-fab5f8f9e5fe.png)

**Comment by dmpas** [comment]
Забавно.

**Comment by andreevlex** [comment]
Мы при распаковке добавили проверку на ошибку потока, вот теперь выгрузка идет, а данные по факту не выгружаются.

**Comment by andreevlex** [comment]
Кажется нашел!!!
`Class_1CD.cpp`
`bool Field::save_blob_to_file(char* rec, String _filename, bool unpack)`
```c++
if(zipped && maybezipped2)
			{
				if(usetemporaryfiles) _s2 = new TTempStream;
				else _s2 = new TMemoryStream;
				try
				{
					_sx->Seek(0, soFromBeginning);
					ZInflateStream(_sx, _s2);
					zippedContainer = true;
					_sx2 = _s2;
					_s2 = NULL;
					delete _sx;
					_sx = NULL;
				}
				catch (...)
				{
					_sx2 = _sx;
					_sx = NULL;
					delete _s2;
					_s2 = NULL;
				}
			}
```
Вот тут на вход zlib подается уже распакованный массив байт
код выше ожидает исключение, а его zlib не бросает, в итоге в выходной файл получается пустым.

**Comment by dmpas** [comment]
Пробовал бросить исключение?

**Comment by andreevlex** [comment]
да, и blobs не пустые стали.

**Comment by andreevlex** [comment]
@dmpas Надо переписывать код вида 
```c++
try
{
...
ZInflateStream(src, dst);
...
}
catch(...)
{

}
```
Предлагаю, сделать `ZInflateStream` чтобы возвращала `bool` и `try` заменить на `if() else`

**Comment by dmpas** [comment]
Согласен, не дело отлавливать вообще все ошибки, если в частности мы можем отработать только одну.

**Comment by fishca** [comment]
здесь надо понять почему так получается.
у @awa15 код жеж работает, насколько я понимаю.
похоже где-то у нас логическая ошибка, я вчера в первоисточнике смотрел, код один в один.

**Comment by dmpas** [comment]
Логика простая. Мы не знаем точно, какие данные запакованы, а какие нет. Потому просто пытаемся паспаковать всё. Если распаковалось -  было упаковано. Если нет - данные уже как есть.

**Comment by andreevlex** [comment]
Мы тут решили проблему с пустыми файлами при выгрузке?

**Comment by fishca** [comment]
да, данные выгружаются, единственная проблема с распаковкой в EXTERNALS сейчас

**Comment by dmpas** [comment]
@fishca  проверь сборку https://ci.appveyor.com/project/dmpas/tool1cd/build/1.0.0.81/artifacts
