### ISSUE TITLE
Ошибка определения абсолютного пути к файлу базы

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#36]
При отладке указываю в параметрах
`-eax ~/dev-pro/testctool1cd/1cv8ddb_xml ~/dev-pro/testctool1cd/1cv8ddb.1CD`

Получаю содержание переменной 
```c++
dbpath = "/home/ubuntu/dev-pro/tool1cd/~/dev-pro/testctool1cd/1cv8ddb.1CD"
```

**Comment by dmpas** [comment]
определение абсолютного пути в большинстве случаев не имеет смысла и от него нужно избавиться.

**Comment by ava57r** [comment]
Командная оболочка все подстановочные символы заменяет и пути попадают в аргументы развернутыми.
В IDE такое делать не надо.
