### ISSUE TITLE
Создать класс для работы с датой

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#37]
dmpas commented an hour ago

@andreevlex
вынеси работу с датой в отдельный класс, в нём же заведи константу. Переименуй константу 7fff, пространства имён пока оставь.

#35

**Comment by andreevlex** [comment]
вот эти преобразования не реализованы в System.Classes
`LocalFileTimeToFileTime(&lft, ft);`
```c++
bool LocalFileTimeToFileTime(const FILETIME *lpLocalFileTime, LPFILETIME lpFileTime)
{
	return false;
}
```
И вообще как-то все странно
`V8timeToFileTime`
не модифицирует переменную ft.

**Comment by andreevlex** [comment]
Про UNIX время забыли еще
https://stackoverflow.com/questions/6161776/convert-windows-filetime-to-second-in-unix-linux

**Comment by andreevlex** [comment]
@dmpas 

```c++
typedef struct _FILETIME {
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
} FILETIME, *PFILETIME;
LocalFileTimeToFileTime
FileTimeToLocalFileTime
```
Все это windows зависимое.
Надо отдельно прописать для разных систем трансформацию времени в v8time

**Comment by dmpas** [comment]
Да, это всё не реализовано. Windows-зависимое переделываем на что-нибудь кросс-платформенное. Или вообще выпилить, если есть вариант сделать проще.

**Comment by andreevlex** [comment]
boost Struct FILETIME
http://live.boost.org/doc/libs/1_58_0/doc/html/boost/date_time/winapi/FILETIME.html

**Comment by andreevlex** [comment]
boost date_time
http://live.boost.org/doc/libs/1_64_0/doc/html/date_time/doxy.html

**Comment by andreevlex** [comment]
Время в формате Filetime используется для задания времени файла, а это спецично для файловой системы, кроссплатформенности не получается.

**Comment by dmpas** [comment]
Мы будем класс пилить или оставим на текущем функционале?

**Comment by ava57r** [comment]
если не будем, то в коде постоянно будем заниматься преобразованием туда сюда.
Думаю удобно будет скрыть реализацию этого под один классом.

**Comment by dmpas** [comment]
@fishca ты ещё готов трудиться над этим вопросом? что скажешь про всё это?

**Comment by fishca** [comment]
> Думаю удобно будет скрыть реализацию этого под один классом.

Думаю надо в эту сторону двинуться

**Comment by ava57r** [comment]
ну что надо делать раз решили.
Я начинаю разбираться.
