### ISSUE TITLE
Выгрузка blob

### ISSUE THREAD

**Issue by fishca** [dmpas/tool1cd#43]
![19_06](https://user-images.githubusercontent.com/1484649/27264306-76d5d986-5484-11e7-8d5a-06c22a41fba4.png)
Из-за этого изменения выгрузка 
![19_06_1](https://user-images.githubusercontent.com/1484649/27264384-c40dacf0-5485-11e7-9580-2cf883621d49.png)
формируется неправильно.

**Comment by dmpas** [comment]
а правильно как?

**Comment by andreevlex** [comment]
были guid вместо имен с частями в виде цифр в конце, но данная проверка не ломает - это защита. Проблема где-то в вызывающем коде.

Думаю вот эта проверка сломала
https://github.com/dmpas/tool1cd/commit/439acfae28a3328f77ac1b9bc1e5a9008e7e9848
https://github.com/dmpas/tool1cd/pull/7

**Comment by fishca** [comment]
w_src - здесь в виде строки guid, limit_size == 0, соответственно условие не срабатывает.
возвращается пустая строка

**Comment by dmpas** [comment]
если `limit_size == 0`, то должна быть пустая строка - я на это уже в каком-то другом месте нарвался и потому так и запилил.

**Comment by fishca** [comment]
При этом распаковка падает на EXTERNALS на файле хранилища, который я выкладывал.
Если limit_size убрать, то распаковка происходит успешно

**Comment by andreevlex** [comment]
Это значит, что цикл должен выполнится хоть раз для успешной распаковки, а мы его проверкой превращаем в пустую строку.

**Comment by dmpas** [comment]
чо??

**Comment by andreevlex** [comment]
Я к тому, что надо отладкой смотреть какой код вызывает этот и решать проблему там, а не править один участок. 
Надо много дебага, чтобы выявить все ситуации.

**Comment by dmpas** [comment]
не надо много дебага. Случаев вызова именно этого конструктора не так уж и много.

**Comment by andreevlex** [comment]
Вот тут выясняли почему надо проверять `limit_size > 0` 
https://github.com/dmpas/tool1cd/pull/24

**Comment by fishca** [comment]
String GUIDasMS(const unsigned char* fr)
{
	int i, j;
	WCHART buf[37];
	WCHART sym;
...
return buf; <--- здесь вызывается конструктор String() (String::String(const WCHART *w_src, int limit_size))
при этом limit_size соответственно нулевой.
}
т.е. надо все такие вызовы переделать на правильный вызов конструктора, я правильно понимаю?

**Comment by dmpas** [comment]
Тогда в String надо по аналогии с `char*` сделать два конструктора для `WCHART`, чтобы не было вот этого со значением по-умолчанию.

**Comment by andreevlex** [comment]
Мы решили проблему с именами файлом с GUID в имени?

**Comment by fishca** [comment]
да, это починилось изменением вызова конструктора 
return String(buf, GUID_LEN+1); в Common.cpp

**Comment by dmpas** [comment]
@fishca проверишь, проявляется ли проблема на последней сборке?

**Comment by fishca** [comment]
Проблема исправлена
