### ISSUE TITLE
Ошибка распаковки поля EXTDATA таблицы EXTERNALS при установленных параметрах ActionXMLSaveBLOBToFileChecked = true ActionXMLUnpackBLOBChecked = true

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#50]
При распаковке таблицы `EXTERNALS` файла 1cv8ddb по ключу `-eax`
программа падает на строке
```c++
int64_t TMemoryStream::Read(void *Buffer, int64_t Count)
...
memcpy(Buffer, _data.data() + m_position, toRead);
...
```
Стэк
`m_position = -1944278050`
`toRead = 1944286741`

Список вызовов
```c++
int64_t TMemoryStream::Read(void *Buffer, int64_t Count)
TStream* read_block(TStream* stream_from, int start, TStream* stream_to = NULL)
void v8catalog::initialize()
```
Причина в этом куске кода
```c++
_fat = read_block(data, 16);
_fat->Seek(0, soFromBeginning);
_countfiles = _fat->GetSize() / 12;
for(int i = 0; i < _countfiles; i++){
	_fat->Read(&_fi, 12);
	read_block(data, _fi.header_start, _file_header);
	_file_header->Seek(0, soFromBeginning);
	_temp_buf = new char[_file_header->GetSize()];
	_file_header->Read(_temp_buf, _file_header->GetSize());
	_name = (WCHART*)(_temp_buf + 20);
	_file = new v8file(this, _name, _prev, _fi.data_start, _fi.header_start, (int64_t*)_temp_buf, (int64_t*)(_temp_buf + 8));
	delete[] _temp_buf;
	if(!_prev) first = _file;
	_prev = _file;
}
```
`_fat->GetSize()  = 24`
`countfiles = 2`
Вот на второй итерации грохается.

**Comment by andreevlex** [comment]
В двух проверенных файлах 
`_fat->Read(&_fi, 12);` выдает на первой итерации.
`_fi = Details:{header_start = 2147483647, data_start = 512, ff = 1}`

а судя по определению
```c++
struct fat_item{
	int32_t header_start;
	int32_t data_start;
	int32_t ff;            // всегда 7fffffff
};
```

**Comment by andreevlex** [comment]
В двух проверенных файлах 
`_fat->Read(&_fi, 12);` выдает на первой итерации.
`_fi = Details:{header_start = 2147483647, data_start = 512, ff = 1}`

а судя по определению
```c++
struct fat_item{
	int32_t header_start;
	int32_t data_start;
	int32_t ff;            // всегда 7fffffff
};
```

**Comment by fishca** [comment]
у меня как раз на этом и падает

**Comment by ava57r** [comment]
Поднялся выше по стэку вызова
Падает при попытке сохранить поле 
`<Field Name="EXTDATA" Type="image" Length="0" Precision="0"/>`

**Comment by ava57r** [comment]
Нашел причину

```c++
int64_t TStream::Read(System::DynamicArray<System::t::Byte> &Buffer, int64_t Count)
{
	auto CountToRead = (Count <= 0) ? GetSize() : Count;
	if (Buffer.size() < CountToRead) {
		Buffer.resize(CountToRead);
	}
	//Seek(0, soFromBeginning);
	return Read(Buffer.data(), CountToRead);
}
```
Законтировал проблемную строку.
Поток уже спозиционирован, а тут его мы сбрасываем в начало и читаются не данные, читается заголовок.
Это изменение добавили мы, предлагаю посмотреть историю с конца мая.

**Comment by ava57r** [comment]
Распаковка до конца все равно не проходит.
Падает на сохранении в файлы
```c++
void v8catalog::SaveToDir(String DirName)
```

**Comment by fishca** [comment]
Очень похоже что этот код в разных местах чтения должен по разному позиционироваться. И эту строку вроде как я добавлял, надо посмотреть.

**Comment by ava57r** [comment]
Позиционирование возложено на вызывающий код, внутри метода делать это не надо.
вот пример
```c++
TStream* read_block(TStream* stream_from, int start, TStream* stream_to = NULL)
```
Данный метод спозиционировал поток перед копированием.

**Comment by ava57r** [comment]
PR #63 исправил проблему
