### ISSUE TITLE
Изменить код использующий ZInflateStream

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#51]
Использование ZInflateStream обрамляется в try блоки, но данная функция не генерирует исключений и код, который ее использует подобным образом работает не правильно.

**Comment by andreevlex** [comment]
@dmpas почему не используем класс `ZStreamBase`

**Comment by dmpas** [comment]
не знаю. Исторически так как-то сложилось. На старте были какие-то сложности с злибом (изначально вообще на аббревиа всё было), потом что-то поправили, что-то переделали. Тут может @fishca подскажет?
