### ISSUE TITLE
Исправить кодировку сообщение выводимых в консоль

### ISSUE THREAD

**Issue by andreevlex** [dmpas/tool1cd#55]
В Windows в консоль выводятся мусор.
Необходимо исправить кодировку текста, который выводиться в консоль.

**Comment by fishca** [comment]
в винде консоль кривая просто, используй нормуль консоль в виде ConEmu и будет счастье :)

**Comment by andreevlex** [comment]
Мы будем использовать. А другие как?

**Comment by fishca** [comment]
пусть все остается в Unicode как есть, кому надо тот поправит кодировку в консоли

**Comment by andreevlex** [comment]
можно справиться и с обычной консолью.
последовательность команд
```cmd
chcp 1251
.\tool1cd.exe
```
выдает все норм.

последовательность команд
```cmd
chcp 1251
.\tool1cd.exe -h
```
выдает мусор.

последовательность команд
```cmd
chcp 65001
.\tool1cd.exe -h
```
выдает норм, кроме команды
```cmd
.\tool1cd.exe
```

**Comment by dmpas** [comment]
Какой-то из исходников не в утф-8???

**Comment by andreevlex** [comment]
в `cTool_1CD_Main.cpp` есть такой код
```c++
if(commands.get_length() == 0)
	{
		cout << "cTool_1CD (c) awa 2009 - 2017" << endl << "Запусти cTool_1CD -h для справки" << endl;
		return 0;
	}
```
В нем причина.

**Comment by dmpas** [comment]
Если сам файл в утф-8, то с ним не должно быть косяков при chcp 65001

**Comment by andreevlex** [comment]
в сборке из github тоже такая ерунда.
Файл utf-8 другие редакторы тоже видят нормально.
